// AUTO-GENERATED FILE. Do not edit.
// Generated by scripts/generate-music-list.mjs
export type MusicItem = { filename: string; releaseSlug: string; src: string; cover?: string };
export const musicItems: MusicItem[] = [
  {
    "filename": "citrus-single_シトラス.mp3",
    "releaseSlug": "citrus-single",
    "src": "/music/citrus-single_シトラス.mp3",
    "cover": "https://res.cloudinary.com/djzxpyzu3/image/upload/v1760692036/citrus_vkmnqa.jpg"
  },
  {
    "filename": "distant-light-single_遠灯.mp3",
    "releaseSlug": "distant-light-single",
    "src": "/music/distant-light-single_遠灯.mp3",
    "cover": "https://res.cloudinary.com/djzxpyzu3/image/upload/v1761729726/IMG_0750_te5d3r.jpg"
  }
];
