name: Actions Build & FTP deploy (main & test, Lolipop)

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - "src/**"
      - "public/**"
      - "scripts/**"
      - "package.json"
      - "package-lock.json"
      - "astro.config.*"
  workflow_dispatch:

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      ref: "main"
    secrets:
      FTP_HOST: ${{ secrets.FTP_HOST }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}

  deploy-tetetest:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy.yml
    with:
      ref: "develop"
      base_path: "/tetetest/"
    secrets:
      FTP_HOST: ${{ secrets.FTP_HOST }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_REMOTE_DIR: ${{ endsWith(secrets.FTP_REMOTE_DIR, '/') && format('{0}tetetest/', secrets.FTP_REMOTE_DIR) || format('{0}/tetetest/', secrets.FTP_REMOTE_DIR) }}
